Добавил вспомогательные функции
htmlacademy-javascript/518263-keksobooking-25 pull request #2
Opened 2022-02-19 14:35 UTC by Metaliy

2022-02-19 20:20 UTC, KletskovG requested changes
Надо в некоторых местах пофиксить опечатки

2022-02-19 20:20 UTC, KletskovG commented on js/main.js
> +const getRamdomNumber = function(minNumber, maxNumber) {
getRamdomNumber -> getRandomNumber

2022-02-19 20:20 UTC, KletskovG commented on js/main.js
> +const getFractionalRamdomNumber = function(minNumber, maxNumber, digit) {
getFractionalRamdomNumber -> getFractionalRandomNumber

2022-02-19 20:20 UTC, KletskovG commented on js/main.js
> +'use scrict';
'use script' -> 'use strict'

2022-02-20 02:02 UTC, Metaliy reviewed
При исправлении: 'use script' -> 'use strict'
Линтер выдал вот это:
'use [strict](https://eslint.org/docs/rules/strict)' is unnecessary inside of modules.eslintstrict

2022-02-20 07:30 UTC, KletskovG approved these changes
Все ок!

2022-02-20 07:30 UTC, merged